// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token  string  `json:"token"`
	Author *Author `json:"author"`
}

type Author struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	Bio       *string `json:"bio,omitempty"`
	Role      string  `json:"role"`
	Posts     []*Post `json:"posts"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type Category struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Slug      string  `json:"slug"`
	Posts     []*Post `json:"posts"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewAuthor struct {
	Name     string  `json:"name"`
	Email    string  `json:"email"`
	Bio      *string `json:"bio,omitempty"`
	Password string  `json:"password"`
}

type NewCategory struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type NewPost struct {
	Title       string   `json:"title"`
	Slug        string   `json:"slug"`
	Description *string  `json:"description,omitempty"`
	Content     string   `json:"content"`
	Published   *bool    `json:"published,omitempty"`
	AuthorID    string   `json:"authorId"`
	CategoryIds []string `json:"categoryIds,omitempty"`
}

type Post struct {
	ID          string      `json:"id"`
	Title       string      `json:"title"`
	Slug        string      `json:"slug"`
	Description *string     `json:"description,omitempty"`
	Content     string      `json:"content"`
	Published   bool        `json:"published"`
	Author      *Author     `json:"author"`
	Categories  []*Category `json:"categories"`
	CreatedAt   string      `json:"createdAt"`
	UpdatedAt   string      `json:"updatedAt"`
}

type Query struct {
}

type RegisterInput struct {
	Name     string  `json:"name"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Bio      *string `json:"bio,omitempty"`
}

type Session struct {
	ID        string `json:"id"`
	AuthorID  string `json:"authorId"`
	Token     string `json:"token"`
	ExpiresAt string `json:"expiresAt"`
}

type UpdateAuthor struct {
	ID       string  `json:"id"`
	Name     *string `json:"name,omitempty"`
	Email    *string `json:"email,omitempty"`
	Bio      *string `json:"bio,omitempty"`
	Password *string `json:"password,omitempty"`
}

type UpdateAuthorRoleInput struct {
	AuthorID string `json:"authorId"`
	Role     string `json:"role"`
}

type UpdateCategory struct {
	ID   string  `json:"id"`
	Name *string `json:"name,omitempty"`
	Slug *string `json:"slug,omitempty"`
}

type UpdatePost struct {
	ID          string   `json:"id"`
	Title       *string  `json:"title,omitempty"`
	Slug        *string  `json:"slug,omitempty"`
	Description *string  `json:"description,omitempty"`
	Content     *string  `json:"content,omitempty"`
	Published   *bool    `json:"published,omitempty"`
	CategoryIds []string `json:"categoryIds,omitempty"`
}
